server:
  port: 1111
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://192.168.0.164:1111/eureka/
  instance:
    # 开启IP访问
    ip-address: true
spring:
  application:
    name: eureka-server