server:
  port: 1111
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://192.168.1.150:1111/eureka/
  instance:
    # 开启IP访问
    ip-address: true
  server:
    # 关闭保护机制
    enable-self-preservation: false
spring:
  application:
    name: eureka-server