spring:
  application:
    name: server-provider-1
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      # 在高可用环境下只需要注册到其中一个eureka-server，因为eureka-server之间会相互同步信息
      defaultZone: http://localhost:1111/eureka/
      # 把服务注册到eureka，该值默认为true，如果是false将不注册到eureka
    register-with-eureka: true
    instance:
      # 服务续约超时时间，默认为90秒，即90秒eureka未收到续约请求的服务将被下线
      lease-expiration-duration-in-seconds: 15
      # 服务续约时间间隔，默认为30秒，即多久当前应用向注册中心发起一次心跳检测
      lease-renewal-interval-in-seconds: 5
server:
  port: 9002
