server:
  port: 1112
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://eureka-server-1:1111/eureka/
  instance:
    hostname: eureka-server-2

spring:
  application:
    name: eureka-server