server:
  port: 2222
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://localhost:1111/eureka/
  instance:
    # 开启IP访问
    ip-address: true
spring:
  application:
    name: eureka-server
