spring:
  application:
    name: server-consumer-1
eureka:
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://localhost:1111/eureka/
    # 表示经过多长时间拉取一次服务列表，单位秒
    registry-fetch-interval-seconds: 20
server:
  port: 8080
